openapi: 3.0.0
info:
  title: Moonbag API
  description: API for the Moonbag automated portfolio management system
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Development server
paths:
  /api/wallets/add:
    post:
      summary: Add a new wallet to track
      tags: [Wallets]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                  description: Ethereum address to track
      responses:
        201:
          description: Wallet added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  wallet:
                    type: object
                    properties:
                      address:
                        type: string
                      inhouse_wallet_address:
                        type: string
                      balance:
                        type: string
        500:
          description: Server error

  /api/wallets/remove:
    delete:
      summary: Remove a tracked wallet
      tags: [Wallets]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
      responses:
        200:
          description: Wallet removed successfully
        500:
          description: Server error

  /api/wallets/update:
    post:
      summary: Update moonbag percentage for a wallet
      tags: [Wallets]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                moonbag_percent:
                  type: number
                address:
                  type: string
      responses:
        200:
          description: Percentage updated successfully
        500:
          description: Server error

  /api/wallets/get/{wallet_address}:
    get:
      summary: Get wallet details
      tags: [Wallets]
      parameters:
        - in: path
          name: wallet_address
          required: true
          schema:
            type: string
      responses:
        200:
          description: Wallet details retrieved successfully
        500:
          description: Server error

  /api/wallets/list:
    get:
      summary: List all tracked wallets
      tags: [Wallets]
      responses:
        200:
          description: List of all wallets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                    inhouse_wallet_address:
                      type: string
                    balance:
                      type: string
        500:
          description: Server error

  /api/transaction/{wallet_address}:
    get:
      summary: Get transactions for a wallet
      tags: [Transactions]
      parameters:
        - in: path
          name: wallet_address
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    original_tx_hash:
                      type: string
                    buyback_tx_hash:
                      type: string
                    token_address:
                      type: string
                    sell_amount:
                      type: string
                    buyback_amount:
                      type: string
        500:
          description: Server error

  /api/transaction/stats/{wallet_address}:
    get:
      summary: Get transaction statistics for a wallet
      tags: [Transactions]
      parameters:
        - in: path
          name: wallet_address
          required: true
          schema:
            type: string
      responses:
        200:
          description: Transaction statistics
        500:
          description: Server error

  /api/transaction/stats/{wallet_address}/{token_address}:
    get:
      summary: Get statistics for a specific token
      tags: [Transactions]
      parameters:
        - in: path
          name: wallet_address
          required: true
          schema:
            type: string
        - in: path
          name: token_address
          required: true
          schema:
            type: string
      responses:
        200:
          description: Token statistics
        500:
          description: Server error

components:
  schemas:
    Wallet:
      type: object
      properties:
        id:
          type: integer
        address:
          type: string
        inhouse_wallet_address:
          type: string
        balance:
          type: string
        moonbag_percent:
          type: integer
        created_at:
          type: string
          format: date-time
        last_updated:
          type: string
          format: date-time

    Transaction:
      type: object
      properties:
        id:
          type: integer
        wallet_address:
          type: string
        inhouse_wallet_address:
          type: string
        original_tx_hash:
          type: string
        buyback_tx_hash:
          type: string
        token_address:
          type: string
        sell_amount:
          type: string
        buyback_amount:
          type: string
        buyback_percentage:
          type: integer
        status:
          type: string
        created_at:
          type: string
          format: date-time
